import pygame

START_IT_UP = pygame.USEREVENT + 79
OPEN_SETTINGS = pygame.USEREVENT + 89
CLOSE_SETTINGS = pygame.USEREVENT + 99
PLAY_GAME = pygame.USEREVENT + 109
OPEN_MENU = pygame.USEREVENT + 119
CLOSE_MENU = pygame.USEREVENT + 129